name: Checkout
description: "Checkout repositories for index action"
inputs:
  info:
    description: "Repository with info files in format 'owner/repo'"
    required: true
  media:
    description: "Repository with media files in format 'owner/repo'"
    required: true
  state:
    description: "Repository with state file in format 'owner/repo'"
    required: true
  state_ref:
    description: "Branch in state repository where state file is located"
    required: false
    default: "state"
  token:
    description: "Token for cloning repositories"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Clone info
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.info }}
        path: info
        token: ${{ inputs.token }}

    - name: Clone media
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.media }}
        path: media
        token: ${{ inputs.token }}

    - name: Clone info state
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.state }}
        path: finder_state
        ref: ${{ inputs.state_ref }}
        token: ${{ inputs.token }}
