name: index

on:
  repository_dispatch:
    types: [index]
  workflow_dispatch:
    inputs:
      force:
        description: 'Path to media to index, e.g. "Movies/John Wick.yml". Leave empty for normal operation. Set to "all" to re-index all media. Can be comma-separated list.'
        required: false
        default: ""

concurrency:
  group: index
  cancel-in-progress: false

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout repositories
        uses: ./.github/actions/checkout
        with:
          info: alsosee/info
          media: alsosee/media
          state: alsosee/finder
          state_ref: state
          token: ${{ secrets.PKG_TOKEN }}

      - name: Set environment variable (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: alsosee/envset@v1
        with:
          name: FORCE
          value: ${{ github.event.inputs.force }}

      - name: Set environment variable (repository_dispatch)
        if: github.event_name == 'repository_dispatch' && github.event.client_payload.force
        uses: alsosee/envset@v1
        with:
          name: FORCE
          value: ${{ github.event.client_payload.force }}

      - name: Run action
        uses: ./
        with:
          info: ./info
          media: ./media
          state_file: ./finder_state/.state
          ignore_file: .ignore
          host: https://search.alsosee.info
          index: info
          master_key: ${{ secrets.MEILISEARCH_MASTER_KEY }}
          force: ${{ env.FORCE }}

      - name: Commit and push
        shell: bash
        run: |
          cd finder_state
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config --global user.name 'GitHub Actions (index workflow)'
          git config --global user.email 'gha@alsosee.info'
          git add ".state"
          git commit -m "Update index state [skip ci]"
          git push origin state
