name: index

on:
  repository_dispatch:
    types: [index]
  workflow_dispatch:
    inputs:
      force:
        description: 'Path to media to index, e.g. "Movies/John Wick". Leave empty for normal operation. Set to "all" to re-index all media.'
        required: false
        default: ""

concurrency:
  group: index
  cancel-in-progress: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone info
        uses: actions/checkout@v4
        with:
          repository: alsosee/info
          path: info
          token: ${{ secrets.PKG_TOKEN }}

      - name: Clone info state
        uses: actions/checkout@v4
        with:
          repository: alsosee/finder
          path: finder_state
          ref: state
          token: ${{ secrets.PKG_TOKEN }}

      - name: Clone media
        uses: actions/checkout@v4
        with:
          repository: alsosee/media
          path: media
          token: ${{ secrets.PKG_TOKEN }}

      - name: Run action
        uses: ./
        with:
          info: ./info
          media: ./media
          state_file: ./finder_state/.state
          ignore_file: .ignore
          host: https://search.alsosee.info
          index: info
          master_key: ${{ secrets.MEILISEARCH_MASTER_KEY }}
          force: ${{ github.event.inputs.force }}

      - name: Commit and push
        shell: bash
        run: |
          cd finder_state
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config --global user.name 'GitHub Actions (index workflow)'
          git config --global user.email 'gha@alsosee.info'
          git add ".state"
          git commit -m "Update index state [skip ci]"
          git push origin state
