name: index-ru

on:
  repository_dispatch:
    types: [index-ru]
  workflow_dispatch:
    inputs:
      force:
        description: 'Path to media to index, e.g. "Movies/John Wick". Leave empty for normal operation. Set to "all" to re-index all media.'
        required: false
        default: ""

concurrency:
  group: index-ru
  cancel-in-progress: false

jobs:
  index-ru:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout
        with:
          info: alsosee/ru
          media: alsosee/media-ru
          state: alsosee/finder
          state_ref: state-ru

      - name: Run action
        uses: ./.github/actions/ru
        with:
          info: ./info
          media: ./media
          state_file: ./finder_state/.state
          ignore_file: .ignore
          host: https://search.alsosee.info
          index: ru
          master_key: ${{ secrets.MEILISEARCH_MASTER_KEY }}
          force: ${{ github.event.inputs.force }}

      - name: Commit and push
        shell: bash
        run: |
          cd finder_state
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config --global user.name 'GitHub Actions (index workflow)'
          git config --global user.email 'gha@alsosee.info'
          git add ".state"
          git commit -m "Update index state [skip ci]"
          git push origin state
