name: main-ru

on:
  push:
    branches:
      - ru
  pull_request:
  repository_dispatch:
    types: [ru]
  workflow_dispatch:

jobs:
  main-ru:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Go Format
        run: gofmt -s -w -l $(find . -type f -name '*.go'| grep -v "/vendor/") && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest

      - name: Test
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.7.0
        with:
          test-results: test.json

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        if: (github.event_name == 'push' && github.ref == 'refs/heads/ru') || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
        env:
          DOCKER_IMAGE: ghcr.io/alsosee/search-ru
        with:
          registry: ghcr.io
          username: chuhlomin
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          platforms: linux/amd64

      - name: Trigger index
        if: (github.event_name == 'push' && github.ref == 'refs/heads/ru') || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PKG_TOKEN }}
          repository: alsosee/search
          event-type: index-ru
