name: schema-ru

on:
  repository_dispatch:
    types: [schema-ru]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  schema-ru:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ru

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Update Go dependency
        run: |
          GOPROXY="direct" go get -u github.com/alsosee/finder/structs@ru
          go mod tidy
          go mod vendor

          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config --global user.name 'GitHub Actions (schema workflow)'
          git config --global user.email 'gha@alsosee.info'
          git status --porcelain
          git add .
          git commit -m "chore: update structs"
          git push

      - name: Trigger main
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PKG_TOKEN }}
          repository: alsosee/search
          event-type: main-ru
