name: schema

on:
  repository_dispatch:
    types: [schema]
  workflow_dispatch:

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Update Go dependency
        run: |
          GOPROXY="direct" go get -u github.com/alsosee/finder/structs
          go mod tidy
          go mod vendor

          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config --global user.name 'GitHub Actions (schema workflow)'
          git config --global user.email 'gha@alsosee.info'
          git status --porcelain
          git add .
          git commit -m "chore: update structs"
          git push
